// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nauwnggshgiytkkhkcyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hdXduZ2dzaGdpeXRra2hrY3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzU4OTAsImV4cCI6MjA2Mzg1MTg5MH0.20Q1xoy-NqLghTilPqYpKaPCd4HQDd_UWLQK24Pp5w4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);